import React from "react";

function Restaurantlayout({ children, params }) {
  metadata.title = `Menu of ${params.slug}`;
  return <>{children}</>;
}

export const metadata = {
  description: "Generated by Shahin Sharbaf Movassagh",
};

export default Restaurantlayout;
