export const metadata = {
  title: "Search Open Table",
  description: "Generated by Shahin Sharbaf Movassagh",
};

function Restaurantlayout({ children, params }) {
  return (
    <>
      <div className="">{children}</div>
    </>
  );
}

export default Restaurantlayout;
