import React from "react";
import Header from "./components/Header";

function Restaurantlayout({ children, params }) {
  metadata.title = `the ${params.slug}`;
  return (
    <>
      <Header name={params.slug} />
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        {children}
      </div>
    </>
  );
}

export const metadata = {
  description: "Generated by Shahin Sharbaf Movassagh",
};

export default Restaurantlayout;
